# Generated by Django 3.2.3 on 2021-10-31 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='printmodel',
            name='category',
            field=models.CharField(choices=[('japanese', '国語'), ('math', '数学'), ('english', '英語'), ('social_study', '現代社会'), ('chemistry', '化学'), ('biology', '生物'), ('physics', '物理'), ('other', 'その他')], default='japanese', max_length=50),
        ),
    ]
